# netlify.toml
[edge_functions]
  deno_import_map = "netlify/edge-functions/import_map.json"

[[edge_functions]]
  function = "cta"
  path = "/ig/*"

[[edge_functions]]
  function = "cta"
  path = "/x/*"

[[edge_functions]]
  function = "cta"
  path = "/fb/*"
